// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/auth/user/repository/repository.go

// Package mocksrepository is a generated GoMock package.
package mocksrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	repository "github.com/omekov/superapp-backend/internal/auth/user/repository"
)

// MockUserer is a mock of Userer interface.
type MockUserer struct {
	ctrl     *gomock.Controller
	recorder *MockUsererMockRecorder
}

// MockUsererMockRecorder is the mock recorder for MockUserer.
type MockUsererMockRecorder struct {
	mock *MockUserer
}

// NewMockUserer creates a new mock instance.
func NewMockUserer(ctrl *gomock.Controller) *MockUserer {
	mock := &MockUserer{ctrl: ctrl}
	mock.recorder = &MockUsererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserer) EXPECT() *MockUsererMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserer) Create(ctx context.Context, user repository.User) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUsererMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserer)(nil).Create), ctx, user)
}

// CreateSession mocks base method.
func (m *MockUserer) CreateSession(ctx context.Context, sess *repository.Session, expire int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, sess, expire)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockUsererMockRecorder) CreateSession(ctx, sess, expire interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockUserer)(nil).CreateSession), ctx, sess, expire)
}

// DeleteCacheUser mocks base method.
func (m *MockUserer) DeleteCacheUser(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCacheUser", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCacheUser indicates an expected call of DeleteCacheUser.
func (mr *MockUsererMockRecorder) DeleteCacheUser(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCacheUser", reflect.TypeOf((*MockUserer)(nil).DeleteCacheUser), ctx, key)
}

// DeleteSessionByID mocks base method.
func (m *MockUserer) DeleteSessionByID(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByID", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionByID indicates an expected call of DeleteSessionByID.
func (mr *MockUsererMockRecorder) DeleteSessionByID(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByID", reflect.TypeOf((*MockUserer)(nil).DeleteSessionByID), ctx, sessionID)
}

// GetByEmail mocks base method.
func (m *MockUserer) GetByEmail(ctx context.Context, email string) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUsererMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserer)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserer) GetByID(ctx context.Context, id uuid.UUID) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsererMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserer)(nil).GetByID), ctx, id)
}

// GetByUsername mocks base method.
func (m *MockUserer) GetByUsername(ctx context.Context, username string) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUsererMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserer)(nil).GetByUsername), ctx, username)
}

// GetCacheByID mocks base method.
func (m *MockUserer) GetCacheByID(ctx context.Context, key string) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheByID", ctx, key)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheByID indicates an expected call of GetCacheByID.
func (mr *MockUsererMockRecorder) GetCacheByID(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheByID", reflect.TypeOf((*MockUserer)(nil).GetCacheByID), ctx, key)
}

// GetSessionByID mocks base method.
func (m *MockUserer) GetSessionByID(ctx context.Context, sessionID string) (repository.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, sessionID)
	ret0, _ := ret[0].(repository.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockUsererMockRecorder) GetSessionByID(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockUserer)(nil).GetSessionByID), ctx, sessionID)
}

// SetCacheUser mocks base method.
func (m *MockUserer) SetCacheUser(ctx context.Context, key string, seconds int, user *repository.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCacheUser", ctx, key, seconds, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCacheUser indicates an expected call of SetCacheUser.
func (mr *MockUsererMockRecorder) SetCacheUser(ctx, key, seconds, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCacheUser", reflect.TypeOf((*MockUserer)(nil).SetCacheUser), ctx, key, seconds, user)
}

// UpdatePassword mocks base method.
func (m *MockUserer) UpdatePassword(ctx context.Context, userID uuid.UUID, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUsererMockRecorder) UpdatePassword(ctx, userID, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserer)(nil).UpdatePassword), ctx, userID, newPassword)
}

// UpdateState mocks base method.
func (m *MockUserer) UpdateState(ctx context.Context, userID uuid.UUID, state, pinCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateState", ctx, userID, state, pinCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateState indicates an expected call of UpdateState.
func (mr *MockUsererMockRecorder) UpdateState(ctx, userID, state, pinCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateState", reflect.TypeOf((*MockUserer)(nil).UpdateState), ctx, userID, state, pinCode)
}
