name: CICD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  REGISTRY: "ghcr.io/omekov"
  IMAGE_NAME: "superapp-backend"
  CONTAINER_NAME: "superapp-backend"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify dependencies
        run: go mod verify

      - name: Run golang tests
        run: go test -v -cover -timeout 60s ./...
  
  docker_login_build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout docker
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the superapp-backend Docker image
        run: |
          docker build . --tag $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
          docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
  
  deploy:
    runs-on: ubuntu-latest
    needs: docker_login_build_and_push

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
          script: |
            # Login GITHUB Registry
            docker login -u ${{ secrets.GITHUB_TOKEN }} -p ${{ secrets.GITHUB_TOKEN }} $(echo $REGISTRY)
            # Stop running container
            docker stop $(echo $CONTAINER_NAME)
            # Remove old container
            docker rm $(echo $CONTAINER_NAME)
            # Run a new container from a new image
            docker pull $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
            docker run -d --name $(echo $CONTAINER_NAME) --network="host" \
            -v ~/configs/config.yml:/github.com/omekov/superapp-backend/configs/config.yml \
            --restart always \
            --publish 4040:4040 \
            $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)


