name: CICD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify dependencies
        run: go mod verify

      - name: Run golang tests
        run: go test -v -cover -timeout 60s ./...
  
  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the superapp-backend Docker image
        run: |
          docker build . --tag ghcr.io/omekov/superapp-backend:latest
          docker push ghcr.io/omekov/superapp-backend:latest

