name: CICD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -v -cover -timeout 60s ./...